name: alnaiem
description: Athkar Application

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#latest build for andrios
version: 3.0.0+3
#version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  url_launcher: ^6.1.5
  flutter_email_sender: ^5.1.0
  circular_profile_avatar: ^2.0.5
  google_fonts_arabic: ^1.1.7
  sqflite: ^2.0.3+1
  path_provider: ^2.0.11
  share: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - assets/images/backgroungImage.jpg
    - assets/images/eurekalogoIcon.png
    - assets/images/delete.png
    - assets/images/1.jpg
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/4.png
    - assets/images/5.png
    - assets/images/6.png
    - assets/images/7.png
    - assets/images/8.png
    - assets/images/9.png
    - assets/images/10.png
    - assets/images/11.png
    - assets/images/12.png
    - assets/images/13.png
    - assets/images/14.png
    - assets/images/15.png
    - assets/images/16.png
    - assets/images/17.png
    - assets/images/18.png
    - assets/images/19.png
    - assets/images/20.png
    - assets/images/21.png
    - assets/images/22.png
    - assets/images/23.png
    - assets/images/24.png
    - assets/images/25.png
    - assets/images/26.png
    - assets/images/27.png
    - assets/images/28.png
    - assets/images/29.png
    - assets/images/30.png
    - assets/images/31.png
    - assets/images/32.png
    - assets/images/33.png
    - assets/images/34.png
    - assets/images/35.png
    - assets/images/36.png
    - assets/images/37.png
    - assets/images/38.png
    - assets/images/39.png
    - assets/images/40.png
    - assets/images/41.png
    - assets/images/42.png
    - assets/images/43.png
    - assets/images/44.png
    - assets/images/45.png
    - assets/images/46.png
    - assets/images/47.png
    - assets/images/48.png
    - assets/images/49.png
    - assets/images/50.png
    - assets/images/51.png
    - assets/images/52.png
    - assets/images/53.png
    - assets/images/54.png
    - assets/images/55.png
    - assets/images/56.png
    - assets/images/57.png
    - assets/images/58.png
    - assets/images/59.png
    - assets/images/60.png
    - assets/images/61.png
    - assets/images/62.png
    - assets/images/63.png
    - assets/images/64.png
    - assets/images/65.png
    - assets/images/66.png
    - assets/images/67.png
    - assets/images/68.png
    - assets/images/69.png
    - assets/images/70.png
    - assets/images/71.png
    - assets/images/72.png
    - assets/images/73.png
    - assets/images/74.png
    - assets/images/75.png
    - assets/images/76.png
    - assets/images/77.png
    - assets/images/78.png
    - assets/images/79.png
    - assets/images/80.png
    - assets/images/81.png
    - assets/images/82.png
    - assets/images/83.png
    - assets/images/84.png
    - assets/images/85.png
    - assets/images/86.png
    - assets/images/87.png
    - assets/images/88.png
    - assets/images/89.png
    - assets/images/90.png
    - assets/images/91.png
    - assets/images/92.png
    - assets/images/93.png
    - assets/images/94.png
    - assets/images/95.png
    - assets/images/96.png
    - assets/images/97.png
    - assets/images/98.png
    - assets/images/99.png
    - assets/images/100.png
    - assets/images/101.png
    - assets/images/102.png
    - assets/images/103.png
    - assets/images/104.png
    - assets/images/105.png
    - assets/images/106.png
    - assets/images/107.png
    - assets/images/108.png
    - assets/images/109.png
    - assets/images/110.png
    - assets/images/111.png
    - assets/images/112.png
    - assets/images/113.png
    - assets/images/114.png
    - assets/images/115.png
    - assets/images/116.png
    - assets/images/117.png
    - assets/images/118.png
    - assets/images/119.png
    - assets/images/120.png
    - assets/images/121.png
    - assets/images/122.png
    - assets/images/123.png
    - assets/images/124.png
    - assets/images/125.png
    - assets/images/126.png
    - assets/images/127.png
    - assets/images/128.png
    - assets/images/129.png
    - assets/images/130.png
    - assets/images/131.png
    - assets/images/132.png
    - assets/images/133.png
    - assets/images/134.png
    - assets/images/135.png
    - assets/images/136.png
    - assets/images/137.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
